[build]
  # Build command for Jekyll
  command = "bundle exec jekyll build"
  
  # Publish directory (Jekyll's default output)
  publish = "_site"
  
  # Base directory (if your Jekyll site is in a subdirectory)
  # base = ""

[build.environment]
  # Jekyll environment
  JEKYLL_ENV = "production"
  
  # Ruby version (adjust if needed)
  RUBY_VERSION = "3.0"

# Force HTTPS and canonical URLs
[[redirects]]
  from = "http://www.la-villa-paris.com/*"
  to = "https://la-villa-paris.com/:splat"
  status = 301

[[redirects]]
  from = "https://www.la-villa-paris.com/*"
  to = "https://la-villa-paris.com/:splat"
  status = 301

[[redirects]]
  from = "http://la-villa-paris.com/*"
  to = "https://la-villa-paris.com/:splat"
  status = 301

# Redirect old language-specific URLs to main site
[[redirects]]
  from = "/index_en.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/index_de.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/index_fr.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Redirect old photo gallery URLs to new photos page
[[redirects]]
  from = "/Photo_Gallery/*"
  to = "/photos"
  status = 301

# Handle tracking parameters
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = {Query = {gclid = "*"}}

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = {Query = {sa = "*"}}

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = {Query = {ved = "*"}}

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = {Query = {yandex_source = "*"}}

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Error pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 